name: Publish Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Log in to Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up environment variables
      - name: Set Docker image tag
        id: tag_step
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi
        # This saves the tag into the environment variable `IMAGE_TAG`

      # Build the Docker image with the computed tag
      - name: Build Docker image
        run: |
          echo "Using image tag: $IMAGE_TAG"
          docker build -t ghcr.io/robert-alfaro/grabby:$IMAGE_TAG .

      # Push the Docker image with the computed tag
      - name: Push Docker image
        run: |
          echo "Pushing image with tag: $IMAGE_TAG"
          docker push ghcr.io/robert-alfaro/grabby:$IMAGE_TAG
